### ISSUE TITLE
seq_length less than 256

### ISSUE THREAD

**Issue by vuhongai** [elttaes/Revisiting-PLMs#1]
Dear authors,
Thank you for sharing your work.
I have one question is that why in your dataset preparation codes, you limit the length of the protein to 256 amino acid? Doesn't it impact the performance of the training with different length datasets?

[https://github.com/elttaes/Revisiting-PLMs/blob/78919610a6bf9908ed1eb841bba3d4210840099c/Fitness/flu/esm/dataset/datasets_downstream_tape.py#L217-L224](url)

Thank you.
Ai

**Comment by elttaes** [comment]
Hi Ai,
        In fitness prediction, the fluorescence prediction task protein sequence length will not exceed 239 amino acids, and the stability prediction task sequence length will not exceed 45 amino acids, so 256 will not impact the performance in fitness prediction. After our tests, setting a length limit of 256 for proteins in other functional prediction tasks works better than using full amino acid prediction. 

Best regards.
